# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bad1192254e8c05afb7567d24814069709c939bfd12d676b0be5232be50593dae0595e5219807d56f1649a91e3068b06d4a64c3574b6a7f44fe9223f7512b67

test:
  secret_key_base: d68e1209fd1919a0ea9acbd57b613df22bd901f312ba6e5b8e9a2949cfe650d773947b3589cb9a94b1356fae34e21cadc6a40c5ce44cc19bad164e48b18f921e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
